package com.yrgo.dataaccess;

import com.yrgo.domain.Call;
import com.yrgo.domain.Customer;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;


import javax.annotation.PostConstruct;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


public class CustomerDaoJdbcTemplateImpl implements CustomerDao {

    private final JdbcTemplate jdbcTemplate;

    private static final String INSERT_SQL = "INSERT INTO CUSTOMER_TBL(CUSTOMER_ID, COMPANY_NAME, EMAIL, PHONE, NOTES)VALUES(?, ?, ?, ?, ?)";
    private static final String UPDATE_SQL = "UPDATE CUSTOMER_TBL SET COMPANY_NAME=?, EMAIL=?, PHONE=?, NOTES=? WHERE CUSTOMER_ID=?";
    private static final String DELETE_SQL = "DELETE FROM CUSTOMER_TBL WHERE CUSTOMER_ID=?";
    private static final String GET_BY_ID_SQL = "SELECT CUSTOMER_ID, COMPANY_NAME, EMAIL, PHONE, NOTES FROM CUSTOMER_TBL WHERE CUSTOMER_ID=?";
    private static final String GET_BY_NAME_SQL = "SELECT CUSTOMER_ID, COMPANY_NAME, EMAIL, PHONE, NOTES FROM CUSTOMER_TBL WHERE COMPANY_NAME=?";
    private static final String GET_ALL_SQL = "SELECT CUSTOMER_ID, COMPANY_NAME, EMAIL, PHONE FROM CUSTOMER_TBL";
    private static final String ADD_CALL_SQL = "INSERT INTO CALL_TBL(CUSTOMER_ID, TIME_AND_DATE, NOTES) VALUES (?,?,?)";
    private static final String JOIN_SQL =
            """
                    SELECT
                        c.CUSTOMER_ID,
                        c.COMPANY_NAME,
                        c.EMAIL,
                        c.PHONE,
                        c.NOTES,
                        ca.TIME_AND_DATE AS CALL_TIME,
                        ca.NOTES AS CALL_NOTES
                    FROM CUSTOMER_TBL c
                    LEFT JOIN CALL_TBL ca ON c.CUSTOMER_ID = ca.CUSTOMER_ID
                    WHERE c.CUSTOMER_ID = ?
                    """;

    @Autowired
    public CustomerDaoJdbcTemplateImpl(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @PostConstruct
    private void createTables() {
        try {
            jdbcTemplate.update("""
                        CREATE TABLE CUSTOMER_TBL (
                            CUSTOMER_ID VARCHAR(50),
                            COMPANY_NAME VARCHAR(255),
                            EMAIL VARCHAR(200),
                            PHONE VARCHAR(50),
                            NOTES VARCHAR(255),
                            PRIMARY KEY (CUSTOMER_ID)
                        )
                    """);
            jdbcTemplate.update("""
                        CREATE TABLE CALL_TBL (
                            CALL_ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
                            CUSTOMER_ID VARCHAR(50),
                            TIME_AND_DATE TIMESTAMP,
                            NOTES VARCHAR(255),
                            PRIMARY KEY (CALL_ID),
                            FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_TBL(CUSTOMER_ID)
                        )
                    """);
        } catch (org.springframework.jdbc.BadSqlGrammarException ex) {
            System.err.println("Tables already exist!");
        }
    }

    @Override
    public void create(Customer customer) {
        jdbcTemplate.update(INSERT_SQL, customer.getCustomerId(),
                customer.getCompanyName(), customer.getEmail(),
                customer.getTelephone(), customer.getNotes());
    }


    @Override
    public Customer getById(String customerId) throws RecordNotFoundException {
        return jdbcTemplate.queryForObject(GET_BY_ID_SQL, new CustomerRowMapper(), customerId);
    }

    @Override
    public List<Customer> getByName(String name) {
        return jdbcTemplate.query(GET_BY_NAME_SQL, new CustomerRowMapper(), name);
    }

    @Override
    public void update(Customer customerToUpdate) throws RecordNotFoundException {
        jdbcTemplate.update(UPDATE_SQL, customerToUpdate.getCustomerId(),
                customerToUpdate.getCompanyName(), customerToUpdate.getTelephone(),
                customerToUpdate.getEmail(), customerToUpdate.getNotes());
    }

    @Override
    public void delete(Customer oldCustomer) throws RecordNotFoundException {
        jdbcTemplate.update(DELETE_SQL, oldCustomer.getCustomerId());
    }

    @Override
    public List<Customer> getAllCustomers() {
        return jdbcTemplate.query(GET_ALL_SQL, new CustomerDetailsRowMapper(), false);
    }

    @Override
    public Customer getFullCustomerDetail(String customerId) throws RecordNotFoundException {
        List<Customer> customers = jdbcTemplate.query(JOIN_SQL, new CustomerDetailsRowMapper(), customerId);

        if (customers.isEmpty()) {
            throw new RecordNotFoundException();
        }

        return customers.get(0);
    }

    @Override
    public void addCall(Call newCall, String customerId) throws RecordNotFoundException {
        jdbcTemplate.update(ADD_CALL_SQL, customerId, newCall.getTimeAndDate(), newCall.getNotes());
    }

    private class CustomerRowMapper implements RowMapper<Customer> {
        @Override
        public Customer mapRow(ResultSet rs, int rowNum) throws SQLException {
            String customerId = rs.getString(1);
            String companyName = rs.getString(2);
            String email = rs.getString(3);
            String phone = rs.getString(4);
            String notes = rs.getString(5);

            return new Customer("" + customerId, companyName,
                    email, phone, notes);
        }
    }

    private class CustomerDetailsRowMapper implements RowMapper<Customer> {
        @Override
        public Customer mapRow(ResultSet rs, int rowNum) throws SQLException {
            String customerId = rs.getString(1);
            String companyName = rs.getString(2);
            String email = rs.getString(3);
            String phone = rs.getString(4);
            String customerNotes = rs.getString(5);

            Customer customer = new Customer("" + customerId, companyName,
                    email, phone, customerNotes);

            List<Call> calls = new ArrayList<>();

            do {
                Date callTime = rs.getTimestamp("CALL_TIME");
                String callNotes = rs.getString("CALL_NOTES");

                if (callTime != null) {
                    Call call = new Call(callNotes, callTime);
                    calls.add(call);
                }

            } while (rs.next() && rs.getString("CUSTOMER_ID").equals(customerId));

            customer.setCalls(calls);

            return customer;
        }
    }

}
